language: python
python:
  - 2.7
  - 3.4

env:
  - DJANGO="django<1.9" DJANGO_CMS="django-cms==3.4.4"
  - DJANGO="django<1.10" DJANGO_CMS="django-cms==3.4.4"
  - DJANGO="django<1.11" DJANGO_CMS="django-cms==3.4.2"
  - DJANGO="django<1.11" DJANGO_CMS="django-cms==3.4.3"
  - DJANGO="django<1.11" DJANGO_CMS="django-cms==3.4.4"
  - DJANGO="django<1.11" DJANGO_CMS="django-cms==3.4.5"

install:
  - pip install -r test_requirements.txt
  - pip install -q $DJANGO $DJANGO_CMS
  - python setup.py -q install

script:
  - ./manage.py test
